run:
  timeout: 1m
  
linters:
  enable-all: true
  disable:
    # deprecated
    - maligned
    - scopelint
    - interfacer
    - golint
    - exhaustivestruct
    - nosnakecase
    - structcheck
    - deadcode
    - varcheck
    - ifshort
    # unused
    - nlreturn
    - exhaustruct
    - depguard

output:
  sort-results: true

issues:
  # disable the default limit so we see everything
  max-same-issues: 0
  max-issues-per-linter: 0

  # default enable fix where the linter supports
  fix: true
  exclude-rules:
    # Exclude some linters from testing files.
    - linters:
        - goconst
        - wsl
        - funlen
      path: '.+_test.go'